library(sqldf)
data <- read.csv.sql("household_power_consumption.txt", header=TRUE,sql = 'select * from file where Date == "1/2/2007" or Date == "2/2/2007"', sep=";")
data$Date <- as.Date(data$Date, "%d/%m/%Y")
data$DateTime <- paste(data$Date, data$Time)
data$DateTime <- as.POSIXct(data$DateTime, format = "%Y-%m-%d %H:%M:%S")
par(mar=c(4,4,2,2))
hist(data$Global_active_power,col="red", main="Global Active Power", xlab="Global Active Power(kilowatts)")